const char page1[] PROGMEM =
   "<!DOCTYPE html><html lang=\"en\">\n"
   "<head>\n"
   "<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\"/>\n"
   "<title>WiFi Waterbed Heater</title>\n"
   "<style type=\"text/css\">\n"
   "table,input{\n"
   "border-radius: 5px;\n"
   "box-shadow: 2px 2px 12px #000000;\n"
   "background-image: -moz-linear-gradient(top, #dfffff, #5050ff);\n"
   "background-image: -ms-linear-gradient(top, #dfffff, #5050ff);\n"
   "background-image: -o-linear-gradient(top, #dfffff, #5050ff);\n"
   "background-image: -webkit-linear-gradient(top, #dfffff, #5050ff);\n"
   "background-image: linear-gradient(top, #dfffff, #5050ff);\n"
   "background-clip: padding-box;\n"
   "}\n"
   "body{width:320px;display:block;margin-left:auto;margin-right:auto;text-align:right;font-family: Arial, Helvetica, sans-serif;}}\n"
   "</style>\n"
   "<script type=\"text/javascript\">\n"
   "a=document.all\n"
   "oledon=0\n"
   "avg=1\n"
   "cnt=1\n"
   "function openSocket(){\n"
   "var loc=window.location\n"
   "ws=new WebSocket(\"ws://\"+loc.host+\"/ws\")\n"
   "ws.onopen=function(evt) { }\n"
   "ws.onclose=function(evt) { alert(\"Connection closed.\"); }\n"
   "ws.onmessage=function(evt) {\n"
   " lines=evt.data.split(';')\n"
   " event=lines[0]\n"
   " data=lines[1]\n"
   " if(event=='state')\n"
   " {\n"
   "  d=JSON.parse(data)\n"
   "  dt=new Date(d.t*1000)\n"
   "  a.time.innerHTML=dt.toLocaleTimeString()\n"
   "  a.temp.innerHTML=d.waterTemp.toFixed(1)+'&degF'\n"
   "  a.on.innerHTML=\">\"+d.hiTemp.toFixed(1)+\"&degF \"+(d.on?\"<font color='red'><b>ON</b></font>\":\"OFF\")\n"
   "  a.rt.innerHTML=d.temp.toFixed(1)+'&degF'\n"
   "  a.rh.innerHTML=d.rh.toFixed(1)+'%'\n"
   "  a.tc.innerHTML='$'+d.tc.toFixed(2)\n"
   " }\n"
   " else if(event=='set')\n"
   " {\n"
   "  d=JSON.parse(data)\n"
   "  a.vt.value=d.vt.toFixed(1)\n"
   "  oledon=d.o\n"
   "  a.OLED.value=oledon?'ON ':'OFF'\n"
   "  avg=d.avg\n"
   "  a.AVG.value=avg?'ON ':'OFF'\n"
   "  a.tz.innerHTML=d.tz\n"
   "  a.K.value=d.ppkwh/10000\n"
   "  a.vo.value=d.vo?'ON ':'OFF'\n"
   "  cnt=d.cnt\n"
   "  idx=d.idx\n"
   "  for(i=0;i<8;i++){\n"
   "   item=eval('document.all.r'+i);item.setAttribute('style',i<cnt?'':'display:none')\n"
   "   if(i==idx) item.setAttribute('style','background-color:red')\n"
   "   item=eval('document.all.N'+i);item.value=eval('d.N'+i)\n"
   "   item=eval('document.all.S'+i);item.value=eval('d.S'+i)\n"
   "   item=eval('document.all.T'+i);item.value=eval('d.T'+i)\n"
   "   item=eval('document.all.H'+i);item.value=eval('d.H'+i)\n"
   "  }\n"
   "  a.inc.value=Math.min(8,cnt+1)\n"
   "  a.dec.value=Math.max(1,cnt-1)\n"
   "  a.tc2.innerHTML=d.tc2\n"
   "  a.m.innerHTML=d.m+':'\n"
   " }\n"
   " else if(event=='alert')\n"
   " {\n"
   "  alert(data)\n"
   " }\n"
   "}\n"
   "}\n"
   "function setVar(varName, value)\n"
   "{\n"
   " ws.send('cmd;{\"key\":\"'+a.myKey.value+'\",\"'+varName+'\":'+value+'}')\n"
   "}\n"
   "function oled(){oledon=!oledon\n"
   "setVar('oled',oledon)\n"
   "a.OLED.value=oledon?'ON ':'OFF'\n"
   "}\n"
   "function setavg(){avg=!avg\n"
   "setVar('avg',avg)\n"
   "a.AVG.value=avg?'ON ':'OFF'}\n"
   "function setTZ(){\n"
   "setVar('TZ',a.tz.value)}\n"
   "function setTemp(n){\n"
   "setVar('tadj',n)\n"
   "item=eval('document.all.T'+idx)\n"
   "item.value=+item.value+n\n"
   "}\n"
   "function setVaca(){\n"
   "setVar('vacatemp',a.vt.value)\n"
   "setVar('vaca',(a.vo.value=='OFF')?true:false)\n"
   "a.vo.value=(a.vo.value=='OFF')?'ON ':'OFF'\n"
   "}\n"
   "function setCnt(n){\n"
   "cnt+=n\n"
   "setVar('cnt',cnt)\n"
   "}\n"
   "function setPPK(){\n"
   "setVar('ppkwh',(a.K.value*10000).toFixed())\n"
   "}\n"
   "function setEntry(n){\n"
   "name=eval('document.all.N'+n+'.value')\n"
   "tm=eval('document.all.S'+n+'.value')\n"
   "tp=eval('document.all.T'+n+'.value')\n"
   "th=eval('document.all.H'+n+'.value')\n"
   "ws.send('cmd;{\"key\":\"'+a.myKey.value+'\",\"N'+n+'\":\"'+name+'\",\"S'+n+'\":\"'+tm+'\",\"T'+n+'\":\"'+tp+'\",\"H'+n+'\":\"'+th+'\"}')\n"
   "}\n"
   "</script>\n"
   "</head>\n"
   "<body bgcolor=\"silver\" onload=\"{\n"
   "key=localStorage.getItem('key')\n"
   "if(key!=null) document.getElementById('myKey').value=key\n"
   "openSocket()\n"
   "}\">\n"
   "<h3>WiFi Waterbed Heater</h3>\n"
   "<table align=\"right\">\n"
   "<tr><td align=\"center\" colspan=2><div id=\"time\"></div></td><td><div id=\"temp\"></div> </td><td align=\"center\"><div id=\"on\"></div></td></tr>\n"
   "<tr><td align=\"center\" colspan=2>Bedroom: </td><td><div id=\"rt\"></div></td><td align=\"left\"><div id=\"rh\"></div> </td></tr>\n"
   "<tr><td colspan=2>TZ <input id='tz' type=text size=2 value='-5'><input value=\"Set\" type='button' onclick=\"{setTZ()}\"></td><td colspan=2>Display:<input type=\"button\" value=\"ON \" id=\"OLED\" onClick=\"{oled()}\"></td></tr>\n"
   "<tr><td colspan=2>Vaca:<input id='vt' type=text size=2 value='-10'><input type='button' id='vo' onclick=\"{setVaca()}\"></td>\n"
   "<td colspan=2>Average:<input type=\"button\" value=\"OFF\" id=\"AVG\" onClick=\"{setavg()}\"></td></tr>\n"
   "<tr><td colspan=2>Schedule <input id='inc' type='button' onclick=\"{setCnt(1)}\"><br/>\n"
   "Count <input id='dec' type='button' onclick=\"{setCnt(-1)}\"}></td>\n"
   "<td colspan=2>Temp <input type='button' value='Up' onclick=\"{setTemp(1)}\"><br/>\n"
   "Adjust <input type='button' value='Dn' onclick=\"{setTemp(-1)}\"></td></tr>\n"
   "<tr><td align=\"left\">Name</td><td align=\"left\">Time</td><td align=\"left\">Temp</td><td width=\"99px\" align=\"left\">Threshold</td></tr>\n"
   "<tr><td colspan=4 id='r0' style=\"display:none\"><input name='N0' type=text size=5 value=''>  <input name='S0' type=text size=3 value='6:00'> <input name='T0' type=text size=3 value='82.5F'> <input name='H0' type=text size=2 value='0.5F'> <input value=\"Set\" type='button' onclick=\"{setEntry(0)}\"></td></tr>\n"
   "<tr><td colspan=4 id='r1' style=\"display:none\"><input name='N1' type=text size=5 value=''>  <input name='S1' type=text size=3 value='6:00'> <input name='T1' type=text size=3 value='82.5F'> <input name='H1' type=text size=2 value='0.5F'> <input value=\"Set\" type='button' onclick=\"{setEntry(1)}\"></td></tr>\n"
   "<tr><td colspan=4 id='r2' style=\"display:none\"><input name='N2' type=text size=5 value=''>  <input name='S2' type=text size=3 value='6:00'> <input name='T2' type=text size=3 value='82.5F'> <input name='H2' type=text size=2 value='0.5F'> <input value=\"Set\" type='button' onclick=\"{setEntry(2)}\"></td></tr>\n"
   "<tr><td colspan=4 id='r3' style=\"display:none\"><input name='N3' type=text size=5 value=''>  <input name='S3' type=text size=3 value='6:00'> <input name='T3' type=text size=3 value='82.5F'> <input name='H3' type=text size=2 value='0.5F'> <input value=\"Set\" type='button' onclick=\"{setEntry(3)}\"></td></tr>\n"
   "<tr><td colspan=4 id='r4' style=\"display:none\"><input name='N4' type=text size=5 value=''>  <input name='S4' type=text size=3 value='6:00'> <input name='T4' type=text size=3 value='82.5F'> <input name='H4' type=text size=2 value='0.5F'> <input value=\"Set\" type='button' onclick=\"{setEntry(4)}\"></td></tr>\n"
   "<tr><td colspan=4 id='r5' style=\"display:none\"><input name='N5' type=text size=5 value=''>  <input name='S5' type=text size=3 value='6:00'> <input name='T5' type=text size=3 value='82.5F'> <input name='H5' type=text size=2 value='0.5F'> <input value=\"Set\" type='button' onclick=\"{setEntry(5)}\"></td></tr>\n"
   "<tr><td colspan=4 id='r6' style=\"display:none\"><input name='N6' type=text size=5 value=''>  <input name='S6' type=text size=3 value='6:00'> <input name='T6' type=text size=3 value='82.5F'> <input name='H6' type=text size=2 value='0.5F'> <input value=\"Set\" type='button' onclick=\"{setEntry(6)}\"></td></tr>\n"
   "<tr><td colspan=4 id='r7' style=\"display:none\"><input name='N7' type=text size=5 value=''>  <input name='S7' type=text size=3 value='6:00'> <input name='T7' type=text size=3 value='82.5F'> <input name='H7' type=text size=2 value='0.5F'> <input value=\"Set\" type='button' onclick=\"{setEntry(7)}\"></td></tr>\n"
   "<tr height=32><td id='tc2'></td><td id='m'></td><td><div id='tc'>$0.00</div></td><td>$<input id='K' type=text size=2 value='0.1457'><input value=\"Set\" type='button' onclick=\"{setPPK()}\"></td></tr>\n"
   "<tr><td colspan=2></td><td colspan=2><input id=\"myKey\" name=\"key\" type=text size=40 placeholder=\"password\" style=\"width: 90px\"><input type=\"button\" value=\"Save\" onClick=\"{localStorage.setItem('key', key = document.all.myKey.value)}\"></td></tr>\n"
   "</table>\n"
   "</body>\n"
   "</html>\n";
